export const dynamic = 'force-dynamic'

import { Suspense } from 'react'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Skeleton } from '@/components/ui/skeleton'
import { Nav } from '@/components/nav'
import { MarketsListClient } from '@/components/markets/markets-list-client'
import { Info, AlertCircle } from 'lucide-react'
import { fetchAllActivePolymarketMarkets } from '@/lib/polymarket'
import type { MarketsApiResponse } from '@/lib/types'

async function getMarkets(): Promise<MarketsApiResponse> {
  const markets = await fetchAllActivePolymarketMarkets()
  const uniqueEventIds = new Set(markets.map((m) => m.eventId))
  return {
    scannedAt: new Date().toISOString(),
    eventCount: uniqueEventIds.size,
    marketCount: markets.length,
    markets,
  }
}

function ListSkeleton() {
  return (
    <div className="flex flex-col gap-3">
      {Array.from({ length: 8 }).map((_, i) => (
        <Skeleton key={i} className="h-20 w-full rounded-lg" />
      ))}
    </div>
  )
}

async function MarketsContent() {
  try {
    const data = await getMarkets()
    return <MarketsListClient markets={data.markets} />
  } catch (err) {
    return (
      <Alert variant="destructive">
        <AlertCircle className="size-4" />
        <AlertDescription>
          Failed to load market data:{' '}
          {err instanceof Error ? err.message : 'Unknown error'}. Please try refreshing.
        </AlertDescription>
      </Alert>
    )
  }
}

export default function MarketsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Nav />
      <main className="flex-1 mx-auto w-full max-w-7xl px-4 py-6 sm:px-6 flex flex-col gap-6">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-foreground">All Markets</h1>
          <p className="text-sm text-muted-foreground mt-1 leading-relaxed">
            Browse and filter all scanned Polymarket markets by risk level, volume, and clarity score.
          </p>
        </div>

        <Alert className="border-border bg-muted/40">
          <Info className="size-4 text-muted-foreground" />
          <AlertDescription className="text-xs text-muted-foreground leading-relaxed">
            Data is fetched from the public Polymarket Gamma API. Scores are generated by an independent heuristic model and are not legal or financial advice.
          </AlertDescription>
        </Alert>

        <Suspense fallback={<ListSkeleton />}>
          <MarketsContent />
        </Suspense>
      </main>
    </div>
  )
}
