import Link from 'next/link'
import { ArrowRight, ShieldAlert, BarChart2, BookOpen } from 'lucide-react'

const FEATURES = [
  {
    icon: ShieldAlert,
    title: 'Independent Analysis',
    body: 'No affiliation with any prediction market platform. Every score is generated by a deterministic heuristic model applied uniformly to all markets.',
  },
  {
    icon: BarChart2,
    title: 'Six-Criterion Framework',
    body: 'Time clarity, resolution source quality, outcome definition, evidence standards, edge case handling, and post-trade risk — each scored and explained.',
  },
  {
    icon: BookOpen,
    title: 'Full Methodology',
    body: 'Every scoring rule is documented and publicly available. No black boxes. You can audit exactly why a market received its score.',
  },
]

const STATS = [
  { value: '200+', label: 'Active markets scanned' },
  { value: '6', label: 'Scored criteria' },
  { value: '0–100', label: 'Clarity score range' },
  { value: '5 min', label: 'Cache revalidation' },
]

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      {/* Top bar */}
      <header className="border-b border-border">
        <div className="mx-auto max-w-5xl px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <ShieldAlert className="size-4 text-primary" aria-hidden="true" />
            <span className="font-heading text-base font-medium tracking-wide">Rule Clarity Index</span>
          </div>
          <nav className="flex items-center gap-6" aria-label="Site navigation">
            <Link href="/dashboard" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
              Dashboard
            </Link>
            <Link href="/markets" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
              Markets
            </Link>
            <Link href="/methodology" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
              Methodology
            </Link>
          </nav>
        </div>
      </header>

      <main className="flex-1">
        {/* Hero */}
        <section className="mx-auto max-w-5xl px-6 pt-24 pb-20">
          <div className="max-w-2xl">
            <p className="text-xs uppercase tracking-[0.2em] text-primary font-medium mb-6">
              Independent Watchdog
            </p>
            <h1 className="font-heading text-5xl sm:text-6xl font-light leading-[1.1] tracking-tight text-foreground text-balance mb-6">
              Prediction markets deserve clear rules.
            </h1>
            <p className="text-base text-muted-foreground leading-relaxed max-w-xl mb-10">
              The Rule Clarity Index scans active Polymarket markets in real time and scores each one on six dimensions of resolution quality — so you know exactly how much post-trade risk you are carrying before you trade.
            </p>
            <div className="flex flex-wrap items-center gap-4">
              <Link
                href="/dashboard"
                className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-5 py-2.5 text-sm font-medium hover:opacity-90 transition-opacity"
              >
                View Dashboard
                <ArrowRight className="size-4" aria-hidden="true" />
              </Link>
              <Link
                href="/methodology"
                className="inline-flex items-center gap-2 border border-border text-foreground px-5 py-2.5 text-sm font-medium hover:bg-secondary transition-colors"
              >
                Read the Methodology
              </Link>
            </div>
          </div>
        </section>

        {/* Stats bar */}
        <section className="border-y border-border bg-card" aria-label="Key statistics">
          <div className="mx-auto max-w-5xl px-6 py-10">
            <div className="grid grid-cols-2 gap-8 sm:grid-cols-4">
              {STATS.map((s) => (
                <div key={s.label}>
                  <p className="font-heading text-3xl font-light text-foreground">{s.value}</p>
                  <p className="text-xs text-muted-foreground mt-1 tracking-wide">{s.label}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Features */}
        <section className="mx-auto max-w-5xl px-6 py-20" aria-label="Features">
          <h2 className="font-heading text-3xl font-light text-foreground mb-12">
            Built for rigour, not rhetoric.
          </h2>
          <div className="grid gap-8 sm:grid-cols-3">
            {FEATURES.map(({ icon: Icon, title, body }) => (
              <div key={title} className="flex flex-col gap-3">
                <div className="flex size-8 items-center justify-center border border-border">
                  <Icon className="size-4 text-primary" aria-hidden="true" />
                </div>
                <h3 className="font-heading text-lg font-medium text-foreground">{title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{body}</p>
              </div>
            ))}
          </div>
        </section>

        {/* CTA */}
        <section className="border-t border-border bg-card">
          <div className="mx-auto max-w-5xl px-6 py-16 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6">
            <div>
              <h2 className="font-heading text-2xl font-light text-foreground">
                Start with the highest-risk markets.
              </h2>
              <p className="text-sm text-muted-foreground mt-2">
                Sorted by rule clarity score, lowest first.
              </p>
            </div>
            <Link
              href="/markets?sort=score-asc&risk=Critical"
              className="shrink-0 inline-flex items-center gap-2 bg-primary text-primary-foreground px-5 py-2.5 text-sm font-medium hover:opacity-90 transition-opacity"
            >
              View Critical-Risk Markets
              <ArrowRight className="size-4" aria-hidden="true" />
            </Link>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-border">
        <div className="mx-auto max-w-5xl px-6 py-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <p className="text-xs text-muted-foreground">
            Rule Clarity Index — independent, unaffiliated with Polymarket or any prediction market platform.
          </p>
          <p className="text-xs text-muted-foreground">
            Not legal or financial advice. Scores are heuristic estimates only.
          </p>
        </div>
      </footer>
    </div>
  )
}
