import { notFound } from 'next/navigation'
import { Nav } from '@/components/nav'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Separator } from '@/components/ui/separator'
import { RiskBadge } from '@/components/risk-badge'
import { ScoreGauge } from '@/components/score-gauge'
import { ScoreBreakdown } from '@/components/markets/score-breakdown'
import { RawJsonPanel } from '@/components/markets/raw-json-panel'
import { Info, ExternalLink, Calendar, DollarSign, Droplets, FileText } from 'lucide-react'
import type { MarketsApiResponse, NormalizedMarket } from '@/lib/types'

async function getMarket(id: string): Promise<NormalizedMarket | null> {
  const baseUrl =
    process.env.NEXT_PUBLIC_BASE_URL ??
    (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'http://localhost:3000')

  const res = await fetch(`${baseUrl}/api/polymarket/markets`, {
    next: { revalidate: 300 },
  })

  if (!res.ok) return null

  const data: MarketsApiResponse = await res.json()
  return data.markets.find((m) => m.marketId === id) ?? null
}

function formatVolume(n: number) {
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(2)}M`
  if (n >= 1_000) return `$${(n / 1_000).toFixed(2)}K`
  return `$${n.toFixed(2)}`
}

function formatDate(dateStr: string) {
  if (!dateStr) return '—'
  try {
    return new Date(dateStr).toLocaleString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      timeZoneName: 'short',
    })
  } catch {
    return '—'
  }
}

export default async function MarketDetailPage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params
  const market = await getMarket(id)

  if (!market) notFound()

  const { score } = market

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Nav />
      <main className="flex-1 mx-auto w-full max-w-4xl px-4 py-6 sm:px-6 flex flex-col gap-6">
        {/* Header */}
        <div className="flex flex-col gap-3">
          <div className="flex flex-wrap items-center gap-2">
            {market.eventCategory && (
              <Badge variant="secondary" className="text-xs">
                {market.eventCategory}
              </Badge>
            )}
            <RiskBadge level={score.riskLevel} />
          </div>
          <h1 className="text-lg font-bold tracking-tight text-foreground leading-snug text-balance">
            {market.question}
          </h1>
          {market.eventTitle && (
            <p className="text-sm text-muted-foreground">
              Event: {market.eventTitle}
            </p>
          )}
        </div>

        <Alert className="border-border bg-muted/40">
          <Info className="size-4 text-muted-foreground" aria-hidden="true" />
          <AlertDescription className="text-xs text-muted-foreground leading-relaxed">
            Data is fetched from the public Polymarket Gamma API. Scores are generated by an independent heuristic model and are not legal or financial advice.
          </AlertDescription>
        </Alert>

        {/* Score + Summary */}
        <Card>
          <CardHeader>
            <CardTitle className="text-sm font-semibold">Rule Clarity Assessment</CardTitle>
            <CardDescription className="text-xs">{score.summary}</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            <div className="flex items-center gap-6">
              <ScoreGauge score={score.totalScore} riskLevel={score.riskLevel} size="lg" />
              <div className="flex flex-col gap-1">
                <p className="text-sm font-semibold text-foreground">
                  {score.totalScore}/100 — {score.riskLevel} Risk
                </p>
                <p className="text-xs text-muted-foreground leading-relaxed max-w-xs">
                  {score.riskLevel === 'Low' && 'Resolution criteria are well-specified with low post-trade dispute risk.'}
                  {score.riskLevel === 'Medium' && 'Some ambiguity present. Human review recommended before large positions.'}
                  {score.riskLevel === 'High' && 'Significant rule clarity concerns. Material dispute risk exists.'}
                  {score.riskLevel === 'Critical' && 'Resolution criteria are substantially underspecified. High dispute risk.'}
                </p>
              </div>
            </div>

            {score.flags.length > 0 && (
              <div>
                <p className="text-xs font-semibold text-foreground mb-2">Identified Flags</p>
                <ul className="flex flex-col gap-1.5">
                  {score.flags.map((flag, i) => (
                    <li
                      key={i}
                      className="flex items-start gap-2 text-xs text-muted-foreground leading-relaxed"
                    >
                      <span className="mt-0.5 size-1.5 rounded-full bg-destructive shrink-0" aria-hidden="true" />
                      {flag}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Score Breakdown */}
        <Card>
          <CardHeader>
            <CardTitle className="text-sm font-semibold">Score Breakdown</CardTitle>
            <CardDescription className="text-xs">
              Scores across six weighted criteria
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ScoreBreakdown breakdown={score.breakdown} />
          </CardContent>
        </Card>

        {/* Market Details */}
        <Card>
          <CardHeader>
            <CardTitle className="text-sm font-semibold">Market Details</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            {/* Metadata grid */}
            <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
              <div>
                <p className="text-xs text-muted-foreground flex items-center gap-1">
                  <DollarSign className="size-3" aria-hidden="true" /> Volume
                </p>
                <p className="text-sm font-semibold tabular-nums mt-0.5">
                  {formatVolume(market.volume)}
                </p>
              </div>
              <div>
                <p className="text-xs text-muted-foreground flex items-center gap-1">
                  <Droplets className="size-3" aria-hidden="true" /> Liquidity
                </p>
                <p className="text-sm font-semibold tabular-nums mt-0.5">
                  {formatVolume(market.liquidity)}
                </p>
              </div>
              <div className="col-span-2">
                <p className="text-xs text-muted-foreground flex items-center gap-1">
                  <Calendar className="size-3" aria-hidden="true" /> End Date
                </p>
                <p className="text-sm font-semibold mt-0.5">{formatDate(market.endDate)}</p>
              </div>
            </div>

            <Separator />

            {/* Resolution Source */}
            <div>
              <p className="text-xs text-muted-foreground flex items-center gap-1 mb-1">
                <FileText className="size-3" aria-hidden="true" /> Resolution Source
              </p>
              {market.resolutionSource ? (
                <p className="text-sm leading-relaxed">{market.resolutionSource}</p>
              ) : (
                <Badge variant="outline" className="text-xs text-destructive border-destructive/30">
                  Not specified
                </Badge>
              )}
            </div>

            <Separator />

            {/* Description */}
            <div>
              <p className="text-xs font-semibold text-foreground mb-1.5">Description</p>
              {market.description ? (
                <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-wrap">
                  {market.description}
                </p>
              ) : (
                <p className="text-sm text-muted-foreground italic">No description provided.</p>
              )}
            </div>

            <Separator />

            {/* Outcomes */}
            <div>
              <p className="text-xs font-semibold text-foreground mb-2">Outcomes</p>
              <div className="flex flex-wrap gap-2">
                {market.outcomes.map((outcome, i) => (
                  <div
                    key={outcome}
                    className="flex items-center gap-2 rounded-md border border-border px-3 py-1.5 text-sm"
                  >
                    <span className="font-medium">{outcome}</span>
                    {market.outcomePrices[i] !== undefined && (
                      <span className="text-xs text-muted-foreground tabular-nums">
                        {(market.outcomePrices[i] * 100).toFixed(1)}%
                      </span>
                    )}
                  </div>
                ))}
              </div>
            </div>

            {/* External link */}
            {market.marketSlug && (
              <>
                <Separator />
                <a
                  href={`https://polymarket.com/market/${market.marketSlug}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1.5 text-xs text-primary hover:underline"
                >
                  View on Polymarket
                  <ExternalLink className="size-3" aria-hidden="true" />
                </a>
              </>
            )}
          </CardContent>
        </Card>

        {/* Raw JSON */}
        <RawJsonPanel market={market} />
      </main>
    </div>
  )
}
