export const dynamic = 'force-dynamic'

import { Suspense } from 'react'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Skeleton } from '@/components/ui/skeleton'
import { Nav } from '@/components/nav'
import { StatsCards } from '@/components/dashboard/stats-cards'
import { MarketsTable } from '@/components/dashboard/markets-table'
import { Info, AlertCircle } from 'lucide-react'
import { fetchAllActivePolymarketMarkets } from '@/lib/polymarket'
import type { MarketsApiResponse } from '@/lib/types'

async function getDashboardData(): Promise<MarketsApiResponse> {
  const markets = await fetchAllActivePolymarketMarkets()
  const uniqueEventIds = new Set(markets.map((m) => m.eventId))
  return {
    scannedAt: new Date().toISOString(),
    eventCount: uniqueEventIds.size,
    marketCount: markets.length,
    markets,
  }
}

function DashboardSkeleton() {
  return (
    <div className="flex flex-col gap-6">
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        {Array.from({ length: 4 }).map((_, i) => (
          <Skeleton key={i} className="h-28 w-full rounded-lg" />
        ))}
      </div>
      <Skeleton className="h-96 w-full rounded-lg" />
    </div>
  )
}

async function DashboardContent() {
  let data: MarketsApiResponse
  let error: string | null = null

  try {
    data = await getDashboardData()
  } catch (err) {
    error = err instanceof Error ? err.message : 'Unknown error'
    return (
      <Alert variant="destructive">
        <AlertCircle className="size-4" />
        <AlertDescription>
          Failed to load market data: {error}. Please try refreshing the page.
        </AlertDescription>
      </Alert>
    )
  }

  const sorted = [...data.markets].sort((a, b) => a.score.totalScore - b.score.totalScore)

  return (
    <div className="flex flex-col gap-6">
      <StatsCards markets={data.markets} eventCount={data.eventCount} />

      <div>
        <div className="mb-3 flex items-center justify-between">
          <div>
            <h2 className="text-base font-semibold text-foreground">Active Markets</h2>
            <p className="text-xs text-muted-foreground mt-0.5">
              Sorted by rule clarity score (lowest first) &mdash; scanned{' '}
              {new Date(data.scannedAt).toLocaleTimeString('en-US', {
                hour: '2-digit',
                minute: '2-digit',
              })}
            </p>
          </div>
        </div>
        <MarketsTable markets={sorted} />
      </div>
    </div>
  )
}

export default function DashboardPage() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Nav />
      <main className="flex-1 mx-auto w-full max-w-7xl px-4 py-6 sm:px-6 flex flex-col gap-6">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-foreground">
            Prediction Market Rule Clarity Index
          </h1>
          <p className="text-sm text-muted-foreground mt-1 leading-relaxed">
            Independent heuristic analysis of active Polymarket markets, scored on time clarity, resolution source quality, outcome definition, evidence standards, edge case handling, and post-trade risk.
          </p>
        </div>

        <Alert className="border-border bg-muted/40">
          <Info className="size-4 text-muted-foreground" aria-hidden="true" />
          <AlertDescription className="text-xs text-muted-foreground leading-relaxed">
            Data is fetched from the public Polymarket Gamma API. Scores are generated by an independent heuristic model and are not legal or financial advice.
          </AlertDescription>
        </Alert>

        <Suspense fallback={<DashboardSkeleton />}>
          <DashboardContent />
        </Suspense>
      </main>
    </div>
  )
}
